services:
  comfy-1:
    image: sidaliu/comfyui:comfy-cli
    ports:
      - "56781:8188"
    volumes:
      - ./comfy-1:/home/runner
      - ./comfy-public:/comfy-public
      - /mnt/ramdisk:/ramdisk
    environment:
      - HTTP_PROXY=http://host.docker.internal:17890
      - HTTPS_PROXY=http://host.docker.internal:17890
      - HF_ENDPOINT=https://hf-mirror.com/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]

  comfy-2:
    image: sidaliu/comfyui:comfy-cli
    ports:
      - "56782:8188"
    volumes:
      - ./comfy-2:/home/runner
      - ./comfy-public:/comfy-public
      - /mnt/ramdisk:/ramdisk
    environment:
      - HTTP_PROXY=http://host.docker.internal:17890
      - HTTPS_PROXY=http://host.docker.internal:17890
      - HF_ENDPOINT=https://hf-mirror.com/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]

  comfy-3:
    image: sidaliu/comfyui:comfy-cli
    ports:
      - "56783:8188"
    volumes:
      - ./comfy-3:/home/runner
      - ./comfy-public:/comfy-public
      - /mnt/ramdisk:/ramdisk
    environment:
      - HTTP_PROXY=http://host.docker.internal:17890
      - HTTPS_PROXY=http://host.docker.internal:17890
      - HF_ENDPOINT=https://hf-mirror.com/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]

  comfy-4:
    image: sidaliu/comfyui:comfy-cli
    ports:
      - "56784:8188"
    volumes:
      - ./comfy-4:/home/runner
      - ./comfy-public:/comfy-public
      - /mnt/ramdisk:/ramdisk
    environment:
      - HTTP_PROXY=http://host.docker.internal:17890
      - HTTPS_PROXY=http://host.docker.internal:17890
      - HF_ENDPOINT=https://hf-mirror.com/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]

  comfy-5:
    image: sidaliu/comfyui:comfy-cli
    ports:
      - "56785:8188"
    volumes:
      - ./comfy-5:/home/runner
      - ./comfy-public:/comfy-public
      - /mnt/ramdisk:/ramdisk
    environment:
      - HTTP_PROXY=http://host.docker.internal:17890
      - HTTPS_PROXY=http://host.docker.internal:17890
      - HF_ENDPOINT=https://hf-mirror.com/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]

  comfy-9:
    image: sidaliu/comfyui:comfy-cli
    ports:
      - "56789:8188"
    volumes:
      - ./comfy-9:/home/runner
      - ./comfy-public:/comfy-public
      - /mnt/ramdisk:/ramdisk
    environment:
      - HTTP_PROXY=http://host.docker.internal:17890
      - HTTPS_PROXY=http://host.docker.internal:17890
      - HF_ENDPOINT=https://hf-mirror.com/
      - CLI_ARGS=--enable-cors-header=https://heartai.cn
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]

