services:
  comfy-1:
    image: sidaliu/comfyui:latest
    ports:
      - "56781:8188"
    volumes:
      - /mnt/data/ComfyUI-dockers/comfy-1:/home/runner
      - /mnt/data/comfy-public:/comfy-public
    environment:
      - http_proxy=http://172.17.0.1:17890
      - https_proxy=http://172.17.0.1:17890
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]

  comfy-2:
    image: sidaliu/comfyui:latest
    ports:
      - "56782:8188"
    volumes:
      - /mnt/data/ComfyUI-dockers/comfy-2:/home/runner
      - /mnt/data/comfy-public:/comfy-public
    environment:
      - http_proxy=http://172.17.0.1:17890
      - https_proxy=http://172.17.0.1:17890
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]

  comfy-3:
    image: sidaliu/comfyui:latest
    ports:
      - "56783:8188"
    volumes:
      - /mnt/data/ComfyUI-dockers/comfy-3:/home/runner
      - /mnt/data/comfy-public:/comfy-public
    environment:
      - http_proxy=http://172.17.0.1:17890
      - https_proxy=http://172.17.0.1:17890
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]

  comfy-4:
    image: sidaliu/comfyui:latest
    ports:
      - "56784:8188"
    volumes:
      - /mnt/data/ComfyUI-dockers/comfy-4:/home/runner
      - /mnt/data/comfy-public:/comfy-public
    environment:
      - http_proxy=http://172.17.0.1:17890
      - https_proxy=http://172.17.0.1:17890
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]

  comfy-5:
    image: sidaliu/comfyui:latest
    ports:
      - "56785:8188"
    volumes:
      - /mnt/data/ComfyUI-dockers/comfy-5:/home/runner
      - /mnt/data/comfy-public:/comfy-public
    environment:
      - http_proxy=http://172.17.0.1:17890
      - https_proxy=http://172.17.0.1:17890
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]

  comfy-9:
    image: sidaliu/comfyui:latest
    ports:
      - "56789:8188"
    volumes:
      - /mnt/data/ComfyUI-dockers/comfy-9:/home/runner
      - /mnt/data/comfy-public:/comfy-public
    environment:
      - http_proxy=http://172.17.0.1:17890
      - https_proxy=http://172.17.0.1:17890
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]

